<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Provides compile-time transformation for React components</Description>
    <PackageTags>fsharp;fable;react;html</PackageTags>
    <Authors>Zaid Ajaj</Authors>
    <Version>2.2.0</Version>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <PackageReleaseNotes>Remove redundant declaration of imported React component</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AstUtils.fs" />
    <Compile Include="ReactComponent.fs" />
    <Compile Include="Hook.fs" />
    <Compile Include="PrimitiveElement.fs" />
    <Compile Include="PrimitiveElementWithChildren.fs" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
